### ISSUE TITLE
i-Vortex headunit interface, some help appreciated.

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#10]
I happen to have an i-Vortex to test with; trainer + headunit.
Pairing etc works, PC-mode and buttons not yet.

If I switch from Normal mode to PC-mode, should I see some different display?
In my case nothing happens and up/down buttons change the grade, not message received.

As you see in below trace, I repeat SET PC MODE after the zero-frames to stay-alive."
Any idea?
Thanks for coorperation!

```
19:33:02,088: Dongle    send   : synch=0xa4, len= 2, id=0x4d Request Message      , check=0xbd, info="07 51" msg=0x51
19:33:02,094: Dongle    drop   : synch=0xa4, len= 5, id=0x51 Channel ID           , check=0xc8, info="07 00 00 3e 01" (ch=7, nr=0, ID=62, tt=1)

19:34:05,496: Dongle    receive: synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0xad, info="07 ad 01 00 0d 3e 00 23 f5" [ch=7 p=173(VHU Serial number)]

19:34:05,531: Dongle    send   : synch=0xa4, len= 2, id=0x4d Request Message      , check=0xbd, info="07 51" msg=0x51
19:34:05,744: Dongle    receive: synch=0xa4, len= 5, id=0x51 Channel ID           , check=0x1e, info="07 f5 23 3e 01" (ch=7, nr=9205, ID=62, tt=1)

19:34:05,785: Dongle    send   : synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0x4f, info="07 ac 03 04 00 00 00 00 00" [ch=7 p=172(VHU Set headunit mode)]
19:34:05,786: devAntDongle.write(0x01,"a4 09 4e 07 ac 03 04 00 00 00 00 00 4f")

19:34:05,993: Dongle    send   : synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0xe4, info="07 00 00 00 00 00 00 00 00" [ch=7 p=0(Default data page)]
19:34:05,994: devAntDongle.write(0x01,"a4 09 4e 07 00 00 00 00 00 00 00 00 e4")

19:34:05,995: Dongle    send   : synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0x4f, info="07 ac 03 04 00 00 00 00 00" [ch=7 p=172(VHU Set headunit mode)]
19:34:05,996: devAntDongle.write(0x01,"a4 09 4e 07 ac 03 04 00 00 00 00 00 4f")


19:34:06,516: Dongle    send   : synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0xe4, info="07 00 00 00 00 00 00 00 00" [ch=7 p=0(Default data page)]
19:34:06,519: Dongle    send   : synch=0xa4, len= 9, id=0x4e Broadcast Data       , check=0x4f, info="07 ac 03 04 00 00 00 00 00" [ch=7 p=172(VHU Set headunit mode)]




```

**Comment by totalreverse** [comment]
Yes, the display switches to a "reduced" version.  In "Pure PC" mode you should see a single `"- PC -"` and in "mixed PC mode"  (ac 03 02 00 00 00 00 00) you additionally see "CAD, Speed, Power, HR". 

I'm back home on Tuesday. Then, I can make pictures of the 3 modes.  

~~The logged answer "07 00 00 3e 01" looks like your not receiving anything from the head unit~~
EDIT :  of course you're receiving frames from  "07 f5 23 3e 01" 

You're talking on **frequency 78** with period 3840 ?

**Comment by WouterJD** [comment]
No need for pictures; confirmation that display changes seems enough (it does not change in my case)

I do receive serial# message, so connection is established. Will check though.

As if I send something wrong...

Thanks and have a nice weekend

**Comment by WouterJD** [comment]
Sorry Total; I missed the period setting. Headunit now works as expected.
And if you like say hi on https://www.facebook.com/WJ.Dubbeldam so that I can properly thank you for your reliable support.

**Comment by WouterJD** [comment]
Well...i-Vortex interface works

The headunit seems to operate as follows:
- Normal mode: controls the i-Vortex manually
- PC-mode: does not control the i-Vortex and broadcasts button-press messages
- SpecialMode: displays more info, but still controls the i-Vortex so blocks the control of the i-Vortex

Also:
After pairing with the i-Vortex, a message is receivde with the VortexID. This VortexID is the ANT DeviceID of the headunit.

So one should pair with the i-Vortex first and then (after receiving the VortexID) pair with the headunit. This guarantees that i-Vortex and headunit are linked together. Only relevant for environments with multiple i-Vortex trainers. Unlikely to occur at home.

Hope you can use this for your library.
Ciao!
