### ISSUE TITLE
Genius T2021 Brake Support #101

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#15]
@totalreverse could you have a look at below link please?
https://github.com/WouterJD/FortiusANT/issues/101#issuecomment-669139247

Do you know how to interface to this ANT-device?

**Comment by totalreverse** [comment]
Unfortunately no. I do not own a Genius. 
Maybe I find an affordable used brake on eBay this winter to reverse the protocol. 

The Genius uses the same ANT channel frequency (60 = 0x3c) and period (0x1000 = 4096) as the Bushido. 
Maybe the protocol is similar, too?

Have a look at:

https://github.com/jovial/PyBushido
https://github.com/fluxoid-org/CyclismoProject/wiki/Tacx-Bushido-Brake-protocol

**Comment by WouterJD** [comment]
Thanks, some guys work on https://github.com/WouterJD/FortiusANT/issues/101
Let's see where they come up with

**Comment by WouterJD** [comment]
There are some questions regarding the power curve of FortiusANT.
Below snippet is a part from the manual where I describe the Tacx Trainers that are supported.

It SEEMS there is a correlation between issues and the "New USB head unit" and the "magnetic brake".
I know I asked before, but I try again: could you immagine that a T1932 head unit with a T1901 Magnetic brake must be interfaced differently from a T1932/T1941 combi?
- - - - - -
Behind the head unit there are two types of brakes: magnetic and motor. We assume that the characteristics are hidden by the head unit. Note however that today’s (Nov 2020) experience suggests a correlation between the T1932/T1904 head-units and issues with the magnetic brakes.


Bundle | Brake | Head unit | Remarks
-- | -- | -- | --
T1930 Tacx Fortius | T1941 Motor | T1932 | USB interface tested, see 2.6.2
T1900 Tacx i-Magic | T1901 Magnetic | T1902 | Legacy USB interface tested, see 2.6.3
T???? Tacx Flow | T1901 Magnetic | T1932 | Issues: #102 #143
T???? Tacx i-Magic | ? | T1904 | Issues: #128

**Comment by WouterJD** [comment]
Thanks again for all the info on the wiki!

**Comment by WouterJD** [comment]
FYI:

This is the correlation (today) for Power curve issues:
==> "New USB interface" does not work well with T1901


#Tacx'ers |   |   | Brake |  
-- | -- | -- | -- | --
Pwr   Issue | Head unit | Tacx trainer | T1901 | (blank)
x | T1904 | i-Magic | 1 |  
  | T1932 | Flow | 2 |  
  |   | Fortius |   | 1
  |   | i-Flow |   | 1
  |   | i-Flow VR | 1 |  
  |   | i-Magic | 2 |

**Comment by WouterJD** [comment]
Power Curve is handled in new issue
