### ISSUE TITLE
Tacx Fortius 110V Variants

### ISSUE THREAD

**Issue by TriScott** [totalreverse/ttyT1941#19]
There were at least two 110V variants of the Tacx Fortius powerback + motor brake combination paired with the 1932 headunits.

The initial units suffered from an abrupt resistance cutoff at 40km/h.  The problem was so bad, Tacx offered an upgrade to a "v2" that involved swapping out the powerback and motor brake.  I don't believe the problem affected 220V Tacx Fortius devices.

Are you aware of these variants and do you know what the differences are?

Thanks!

**Comment by totalreverse** [comment]
Unfortunately, I cannot help you. I live in a 230V region.

I recommend to ask your questions in the 'Unofficial Tacx Forum' at https://www.lunicus.org/Forum/
There, you find some veterans knowing the old Fortius US model. 
Maybe it is possible to collect some version numbers from Fortius owners to distinguish between the 'broken' and the 'fixed' t1946?

**Comment by TriScott** [comment]
Thanks anyway.  You seem to be the de facto expert on all legacy Tacx hardware now :)

I have both the 'broken' and 'fixed' units, and curiously both motor brakes are labelled 1941 (not 1946), although the second has a second sticker next to it that reads "1946 110V V2".  Similarly, both powerback units are labelled 1946.50, although the 'fixed' one has a second sticker that reads "110V V2" and a penstroke through the main label possibly attempting to turn the '6' in 1946.50 to a '9'.

I was mainly wondering if the versions had a different resistance / power response that would affect things like FortiusANT that are treating both equivalently.  Same question re: 110V vs 230V units in general.

**Comment by WouterJD** [comment]
I would think that the 110/230V side is separated from the logic, and that tacx would not like themselves to have to support more versions in the software than needed. So I would guess the resistance curve would not be affected by the voltages
