### ISSUE TITLE
Power2Load magic for iMagic

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#4]
totalreverse, you have published the USB interfaces for Fortius but also "the Legacy protocol" for older Tacx trainers.
@fritz-hh and @yegorvin are now working to get FortiusANT working on iMagic. Do you have more info on DesiredForceValue (OUT) and ResistanceValue (IN) in relation to TargetPower, similar to power2loadmagic for the Fortius?

Would be great if you could share such info with us.

Thanks.

**Comment by totalreverse** [comment]
I tried to find an approximation  more than 2 years ago before knowing, that brake calibration is crucial for getting usable results. I used the following model

```
 z1(brk) = d + brk * e       
 z2(brk) = c*sin(brk/a)+b    
 P = z1 * speed + z2 * speed^2
    or:
 F = z1 + z2 * speed
 P = F * speed

with 

brk = IN/OUT - 0x80 

P = power
F = force

```
I made several runs with the following results 

guess| a| b| c| d| e|
--|--|--|--|--|--
 guess1 | 85 |      1.52|       1.0|         14.3058742| 0.000811613017
guess2 |74.8380347| 1.56142716| 0.735762312| 13.7915949| 0.00107680030 
guess4 | 79 |        1.65213394| 1.09196131|  12.5882402| 0.000545285698
guess5 |75.4133716| 1.59032650| 0.819433457| 13.4871348| 0.000999338404
guess6 |75.3500839| 1.58474161| 0.817179504| 13.5293908| 0.00100103945 

I decided to use guess2 ..

You may want to play with value 'd' to correct the power for different calibrated trainer.

**Comment by WouterJD** [comment]
Thanks for quick reaction.

What is your opinion on the next:
Following https://github.com/totalreverse/ttyT1941
`You can load the firmware of the "solid blue" device (FortiusSWPID1942Renum.hex) also to the solid green/yellow/white. The solid green head unit 'magically' converts to a 'solid blue' one. This works at least on the devices I own.`

Does that convert the iMagic from "Legacy" to "New" interface, so that the Fortius interface can be used?

**Comment by WouterJD** [comment]
I got a very strong comment from @yegorvin directing me to @goldenCheetah
https://github.com/WouterJD/FortiusANT/issues/11#issuecomment-591924748

Where you use PowerResistanceFactor = 128866 
the constant for iMagic is legacyPowerResistanceFactor = (1 / 0.0036)

So I adjusted FortiusANT and expect test results from them.
Thanks for your formula's anyway!

**Comment by totalreverse** [comment]
Short answer: "No". 

The controlling of the trainers are utterly different. The firmware controls the trainer and implements the protocol for the communication with the host. It would be possible to run the 1902 firmware on a blue device with minor changes - this would turn a blue device into a green device. But no one needs this. 

I started the development of the "ezTraCon" firmware to change this. The firmware can control the eddy current brakes but talks the Fortius protocol on the USB side. 

Unfortunately it is still not ready to be released. 
Main reason is a missing spin-down calibration together with a verified "power function" for the eddy current brakes. Another reason is the insufficient code quality and documentation.

**Comment by WouterJD** [comment]
Amazing how all these projects come together!
