### ISSUE TITLE
Confused on the legacy/newer 21/48/64 byte interfaces

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#6]
Thanks to your investigations, I could build FortiusANT for the 1932-Fortius, using the "newer" communication protocol.

Then somebody came in using 1902-iMagic and the description for the Legacy protocol could be used.

Today I'm working on the 1942-Fortius, which appears to use the newer protocol with 48 byte messages. No issue; I simply add 16 dummy bytes and leave processing unchanged.

I notice that the wiki has been updated and note the following:
- The table of contents contains broken references (e.g. "Newer USB 12/48 Bytes protocol")
- The setup of the page was "old 23, newer 48, newest 64" (and TOC still is), but the content is mixing the interface age/lengths with the trainer types, being less understandable as it was. My 1932 has the same interface as the 1942 (but is not mentioned), wheras the 1941 is different and described under the section "Newer USB 12/48 Bytes T1942 head unit protocol (USB)".

I would suggest to stay to sections like:
```
USB 'legacy' protocol: 6 Bytes OUT, 21 Bytes IN
     Used by: T1902
     Outbound:
     Inbound:

USB protocol 12 Bytes OUT, 48 Bytes IN
     Used by: T1942
     Outbound:
     Inbound:

USB protocol 12 Bytes OUT, 64 Bytes IN
     Used by: T1904, T1932
     Outbound:
     Inbound:

USB protocol xx Bytes OUT, xx Bytes IN
     Used by: T1941
     Outbound:
     Inbound:

```

would that be possible?

**Comment by totalreverse** [comment]
I know. The Wiki is a collection of several sources without a clear order. In the beginning, there was one large text file, which was a concatenation of several source code snippets and READMEs. 
I tried to order the information and to remove some redundant parts, but this is a lot of work and it does not make any fun. Maybe the last cleanup mixed up some parts ...

**Comment by WouterJD** [comment]
I understand the does-not-make-fun part; but dared to open the topic because of the fundamental work you do.
Take this issue as a credit; I use your wiki as THE interface definition for FortiusANT!
Your work is highly appreciated.

Publishing in C-struct format may be easier than HTML-tables.

Please continue this magnificent piece of work.

**Comment by WouterJD** [comment]
Well 12/48 interface Fortius T1942 is confirmed working. Apparently compatible with 12/64 just buffer is 16bytes shorter. All I did is pass 48 to 64bytes, nothing else😊

**Comment by WouterJD** [comment]
Legacy/New and ANT work. Thanks
