### ISSUE TITLE
Does i-Vortex support SetGrade()

### ISSUE THREAD

**Issue by WouterJD** [totalreverse/ttyT1941#9]
Golden Cheetah defines the function [tacxVortexSetPower()](https://github.com/GoldenCheetah/GoldenCheetah/blob/master/src/ANT/ANTMessage.cpp#L982) and the function tacxVortexSetGrade() would be welcome.

What is your opinion on this?
a- i-Vortex does NOT provide the function setGrade()
b- i-Vortex may provide the function, but we do not know the command
c- i-Vortex provides the function and the command is: [which would be a real bommer]

I'm afraid for answer a) but not question is no answer at all :-)

**Comment by totalreverse** [comment]
Currently I have no answer ... 

I played with the a T2172 vortex head unit this evening. 
It allows to control the brake by setting power, grade or heart rate. 

I tried to emulate a vortex brake (I do not own one) and I was able to let the head unit show emulated values for power, speed, cad, a serial number, a version number and a calibration value. 

Then I set the target power and the grade to several different values and varied the emulated speed and power values from the brake. The only page the head units sends to the brake all the time was a: 
```
4e 00 10 1b 10 55 7e 08 01 89
```
Maybe Answer d) "This needs further investigations". 

I also played with the head unit display modes (head unit acts as a master on this frequency).
```
   Freq=78,Period=3840, DeviceType=0x3e
   page:  [4e ch#] [ac 03 [mode] 00 00 00 00 00] [CheckSum]
```
In mode "2" the display shows CAD, Speed, Power, HR from the brake and you can additionally use the 5 keys.

The head units broadcasts round robin these pages; 
```
4e 00 dd 03 80 00 00 00 00 00 ...
4e 00 ad 01 02 0e 3e 00 1b 10 
4e 00 dd 01 00 00 00 00 00 00 
4e 00 dd 02 00 00 00 00 00 00 
```

And for every press on a display key additionally

`4f 00 dd 10 [key#] 00 00 00 00 [cc]`

Where [cc] is a counter, that increments for every key press. 
Key value mapping is

Key|Number
--|--
Left| 01  
Up| 02
OK| 03
Down| 04
Right| 05

**Comment by WouterJD** [comment]
Thanks for the info; invaluable!

For your information implementation being released shortly:
WouterJD/FortiusANT#46 (Is Tacx i-vortex Supported? ==> YES!)
WouterJD/FortiusANT#84 (54 usb trainer - release 3.0 beta)

**Comment by mattipee** [comment]
If a) then physics should reliably give us a Grade2Power, provided we know how to interpret the speed being reported.

But from an interface point if view, if there is a grade command on the i-Vortex then we can "offload" the calculation to the firmware.

Personally, I don't think it should worry us either way.
